version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "event-sourcing"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-jl0s3dqto0ku"
s3_prefix = "event-sourcing"
region = "eu-west-1"
capabilities = "CAPABILITY_NAMED_IAM"
